name: CI Unit Tests

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup
        timeout-minutes: 30
        uses: ./.github/actions/setup
      - name: Unit tests
        timeout-minutes: 30
        run: ./gradlew test
